[debug] [2020-02-06T03:23:50.189Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:23:50.190Z] Command:       /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/node /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/firebase serve
[debug] [2020-02-06T03:23:50.190Z] CLI Version:   7.12.1
[debug] [2020-02-06T03:23:50.190Z] Platform:      darwin
[debug] [2020-02-06T03:23:50.191Z] Node Version:  v12.13.1
[debug] [2020-02-06T03:23:50.191Z] Time:          Wed Feb 05 2020 21:23:50 GMT-0600 (Central Standard Time)
[debug] [2020-02-06T03:23:50.191Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:23:50.191Z] 
[debug] [2020-02-06T03:23:50.197Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-02-06T03:23:50.198Z] > authorizing via signed-in user
[debug] [2020-02-06T03:23:50.198Z] [iam] checking project organizapp-local for permissions ["firebase.projects.get"]
[debug] [2020-02-06T03:23:50.199Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/organizapp-local:testIamPermissions  

[debug] [2020-02-06T03:23:50.666Z] <<< HTTP RESPONSE 200
[debug] [2020-02-06T03:23:50.669Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/organizapp-local  
 
[debug] [2020-02-06T03:23:50.956Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/juanjosebenitezrodriguez/Documents/sandbox'...
[info] 
[debug] [2020-02-06T03:23:50.966Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at Object.<anonymous> (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:20:39)
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:3:12)
    at Object.start (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:18:16)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:24:40
    at arrayMap (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:23:29
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:3:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-02-06T03:24:16.925Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:24:16.930Z] Command:       /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/node /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/firebase serve --debug
[debug] [2020-02-06T03:24:16.931Z] CLI Version:   7.12.1
[debug] [2020-02-06T03:24:16.932Z] Platform:      darwin
[debug] [2020-02-06T03:24:16.933Z] Node Version:  v12.13.1
[debug] [2020-02-06T03:24:16.935Z] Time:          Wed Feb 05 2020 21:24:16 GMT-0600 (Central Standard Time)
[debug] [2020-02-06T03:24:16.935Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:24:16.935Z] 
[debug] [2020-02-06T03:24:16.948Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-02-06T03:24:16.949Z] > authorizing via signed-in user
[debug] [2020-02-06T03:24:16.949Z] [iam] checking project organizapp-local for permissions ["firebase.projects.get"]
[debug] [2020-02-06T03:24:16.951Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/organizapp-local:testIamPermissions  

[debug] [2020-02-06T03:24:17.393Z] <<< HTTP RESPONSE 200
[debug] [2020-02-06T03:24:17.395Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/organizapp-local  
 
[debug] [2020-02-06T03:24:17.681Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/juanjosebenitezrodriguez/Documents/sandbox'...
[info] 
[debug] [2020-02-06T03:24:17.686Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at Object.<anonymous> (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:20:39)
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:3:12)
    at Object.start (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:18:16)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:24:40
    at arrayMap (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:23:29
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:3:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-02-06T03:25:48.503Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:25:48.507Z] Command:       /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/node /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/firebase serve --debug
[debug] [2020-02-06T03:25:48.507Z] CLI Version:   7.12.1
[debug] [2020-02-06T03:25:48.507Z] Platform:      darwin
[debug] [2020-02-06T03:25:48.507Z] Node Version:  v12.13.1
[debug] [2020-02-06T03:25:48.509Z] Time:          Wed Feb 05 2020 21:25:48 GMT-0600 (Central Standard Time)
[debug] [2020-02-06T03:25:48.509Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:25:48.510Z] 
[debug] [2020-02-06T03:25:48.523Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-02-06T03:25:48.524Z] > authorizing via signed-in user
[debug] [2020-02-06T03:25:48.524Z] [iam] checking project organizapp-local for permissions ["firebase.projects.get"]
[debug] [2020-02-06T03:25:48.526Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/organizapp-local:testIamPermissions  

[debug] [2020-02-06T03:25:49.039Z] <<< HTTP RESPONSE 200
[debug] [2020-02-06T03:25:49.041Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/organizapp-local  
 
[debug] [2020-02-06T03:25:49.317Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/juanjosebenitezrodriguez/Documents/sandbox'...
[info] 
[debug] [2020-02-06T03:25:49.322Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at Object.<anonymous> (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:20:39)
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:3:12)
    at Object.start (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:18:16)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:24:40
    at arrayMap (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:23:29
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:3:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-02-06T03:26:00.916Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:26:00.921Z] Command:       /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/node /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/firebase serve --debug
[debug] [2020-02-06T03:26:00.921Z] CLI Version:   7.12.1
[debug] [2020-02-06T03:26:00.922Z] Platform:      darwin
[debug] [2020-02-06T03:26:00.922Z] Node Version:  v12.13.1
[debug] [2020-02-06T03:26:00.924Z] Time:          Wed Feb 05 2020 21:26:00 GMT-0600 (Central Standard Time)
[debug] [2020-02-06T03:26:00.925Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:26:00.925Z] 
[debug] [2020-02-06T03:26:00.941Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-02-06T03:26:00.942Z] > authorizing via signed-in user
[debug] [2020-02-06T03:26:00.942Z] [iam] checking project organizapp-local for permissions ["firebase.projects.get"]
[debug] [2020-02-06T03:26:00.950Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/organizapp-local:testIamPermissions  

[debug] [2020-02-06T03:26:02.813Z] <<< HTTP RESPONSE 200
[debug] [2020-02-06T03:26:02.819Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/organizapp-local  
 
[debug] [2020-02-06T03:26:03.079Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/juanjosebenitezrodriguez/Documents/sandbox'...
[info] 
[debug] [2020-02-06T03:26:03.091Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at Object.<anonymous> (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:20:39)
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:3:12)
    at Object.start (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:18:16)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:24:40
    at arrayMap (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:23:29
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:3:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-02-06T03:28:08.101Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:28:08.106Z] Command:       /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/node /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/firebase serve --debug
[debug] [2020-02-06T03:28:08.108Z] CLI Version:   7.12.1
[debug] [2020-02-06T03:28:08.108Z] Platform:      darwin
[debug] [2020-02-06T03:28:08.108Z] Node Version:  v12.13.1
[debug] [2020-02-06T03:28:08.112Z] Time:          Wed Feb 05 2020 21:28:08 GMT-0600 (Central Standard Time)
[debug] [2020-02-06T03:28:08.113Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:28:08.114Z] 
[error] 
[error] Error: No project active. Run with --project <projectId> or define an alias by
running firebase use --add
[debug] [2020-02-06T03:29:24.470Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:29:24.473Z] Command:       /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/node /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/firebase serve --debug
[debug] [2020-02-06T03:29:24.474Z] CLI Version:   7.12.1
[debug] [2020-02-06T03:29:24.474Z] Platform:      darwin
[debug] [2020-02-06T03:29:24.474Z] Node Version:  v12.13.1
[debug] [2020-02-06T03:29:24.475Z] Time:          Wed Feb 05 2020 21:29:24 GMT-0600 (Central Standard Time)
[debug] [2020-02-06T03:29:24.476Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:29:24.476Z] 
[error] 
[error] Error: No project active. Run with --project <projectId> or define an alias by
running firebase use --add
[debug] [2020-02-06T03:29:43.526Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:29:43.530Z] Command:       /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/node /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/bin/firebase serve --debug --project organizapp-local
[debug] [2020-02-06T03:29:43.530Z] CLI Version:   7.12.1
[debug] [2020-02-06T03:29:43.530Z] Platform:      darwin
[debug] [2020-02-06T03:29:43.531Z] Node Version:  v12.13.1
[debug] [2020-02-06T03:29:43.532Z] Time:          Wed Feb 05 2020 21:29:43 GMT-0600 (Central Standard Time)
[debug] [2020-02-06T03:29:43.533Z] ----------------------------------------------------------------------
[debug] [2020-02-06T03:29:43.533Z] 
[debug] [2020-02-06T03:29:43.547Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-02-06T03:29:43.547Z] > authorizing via signed-in user
[debug] [2020-02-06T03:29:43.547Z] [iam] checking project organizapp-local for permissions ["firebase.projects.get"]
[debug] [2020-02-06T03:29:43.549Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/organizapp-local:testIamPermissions  

[debug] [2020-02-06T03:29:44.045Z] <<< HTTP RESPONSE 200
[debug] [2020-02-06T03:29:44.047Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/organizapp-local  
 
[debug] [2020-02-06T03:29:44.371Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/juanjosebenitezrodriguez/Documents/sandbox/backOrganiZapp'...
[info] 
[debug] [2020-02-06T03:29:44.376Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/organizapp-local/webApps/-/config  
 
[debug] [2020-02-06T03:29:44.377Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at Object.<anonymous> (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:20:39)
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:3:12)
    at Object.start (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/functions.js:18:16)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:24:40
    at arrayMap (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:23:29
    at Generator.next (<anonymous>)
    at /Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/juanjosebenitezrodriguez/.nvm/versions/node/v12.13.1/lib/node_modules/firebase-tools/lib/serve/index.js:3:12)
[error] 
[error] Error: An unexpected error has occurred.
